# @see https://github.com/release-drafter/release-drafter

name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'release:feature'
  - title: 'Fixes'
    labels:
      - 'release:fix'
  - title: 'Internal changes'
    labels:
      - 'release:internal'
      - 'release:typo'
      - 'chore'
category-template: '### $TITLE'
change-template: '- $TITLE (#$NUMBER)  @$AUTHOR '
version-resolver:
  major:
    labels:
      - 'release:major'
  minor:
    labels:
      - 'release:minor'
  patch:
    labels:
      - 'release:patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
