name: Test laravel projects

on:
  push:
    paths:
      - '**.php'
      - '**.stubphp'
      - 'composer.json'
      - 'tests/laravel*'
      - 'tests/lumen*'
      - '.github/workflows/test-laravel.yml'
  pull_request:
    paths:
      - '**.php'
      - '**.stubphp'
      - 'tests/laravel*'
      - 'tests/lumen*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Laravel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Laravel
      run: |
        ./tests/Application/laravel-test.sh

    - name: Test Lumen
      run: |
        ./tests/Application/lumen-test.sh
