name: Test laravel projects

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Laravel

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test Laravel
      run: |
        ./tests/laravel-test.sh

    - name: Test Lumen
      run: |
        ./tests/lumen-test.sh
