name: Tests

on:
  push:
    paths:
      - '**.php'
      - '**.stubphp'
      - '**.feature'
      - '**.yml'
      - 'composer.json'

  pull_request:
    paths:
      - '**.php'
      - '**.stubphp'
      - '**.feature'
      - 'composer.json'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: composer:v2

      - name: Install composer dependencies
        run: composer install

      - name: Run Unit tests
        run: composer unit

  acceptance_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.1, 8.0]
        illuminate_version: [9.*]
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - php: 8.2
            stability: prefer-lowest

    name: P${{ matrix.php }} | I ${{ matrix.illuminate_version }} | ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.illuminate_version }}" "illuminate/container:${{ matrix.illuminate_version }}" "illuminate/contracts:${{ matrix.illuminate_version }}" "illuminate/database:${{ matrix.illuminate_version }}" "illuminate/http:${{ matrix.illuminate_version }}" "illuminate/support:${{ matrix.illuminate_version }}" --no-interaction --no-progress --prefer-dist --prefer-stable --${{ matrix.stability }}

      - name: Run Acceptance Tests
        run: composer test
