name: Test laravel projects

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - 'tests/laravel*'
      - 'tests/lumen*'
  pull_request:
    paths:
      - '**.php'
      - 'tests/laravel*'
      - 'tests/lumen*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Laravel

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test Laravel
      run: |
        ./tests/laravel-test.sh

    - name: Test Lumen
      run: |
        ./tests/lumen-test.sh
